[package]
name = "amortized_loan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format = "0.4.4"
rust_decimal = "1.28.1"
rust_decimal_macros = "1.28.1"
